@baseEndpoint = http://138.3.214.195

@accessToken = 

###
GET {{baseEndpoint}}/event HTTP/1.1
Authorization: Bearer {{accessToken}}

###
GET {{baseEndpoint}}/event/id/215000 HTTP/1.1
Authorization: Bearer {{accessToken}}

###
GET {{baseEndpoint}}/event/season/4 HTTP/1.1
Authorization: Bearer {{accessToken}}

###
POST {{baseEndpoint}}/event HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "title": "Kubernetesのオートスケーリング",
    "season": "4",
    "presenter": "n",
    "eventDate": "2020-08-11"
}

###
DELETE {{baseEndpoint}}/event HTTP/1.1
Authorization: Bearer {{accessToken}}