apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

images:
- name: nrt.ocir.io/orasejapan/shukawam/auth
  newName: nrt.ocir.io/orasejapan/shukawam/auth
  newTag: e9c5159803d715e9bd482e9d0d2c85d06a830ca9
- name: nrt.ocir.io/orasejapan/shukawam/event
  newName: nrt.ocir.io/orasejapan/shukawam/event
  newTag: e9c5159803d715e9bd482e9d0d2c85d06a830ca9
namespace: ochacafe
