apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

images:
- name: nrt.ocir.io/orasejapan/shukawam/auth
  newName: nrt.ocir.io/orasejapan/shukawam/auth
  newTag: 2f0fe03e80db9a48dec9421268b408725b939e8d
- name: nrt.ocir.io/orasejapan/shukawam/event
  newName: nrt.ocir.io/orasejapan/shukawam/event
  newTag: 2f0fe03e80db9a48dec9421268b408725b939e8d
namespace: ochacafe
